### ISSUE TITLE
inverse_transform?

### ISSUE THREAD

**Issue by Backflipz** [alok-ai-lab/pyDeepInsight#26]
Apologize if this is a dumb question or not fully thought out, but I was wondering if it is feasible to provide an inverse_transform function? I ask because the idea is to use some current generative architectures to produce new images and then re-translate it back to its original form to observe and contextualize what transforms took place. Is this possible or would it not make sense due to the inherent data loss from integer scaling?

**Comment by kaboroevich** [comment]
Implementing an inverse_transform method shouldn't be an issue. We think it's a good idea and will move forward with adding it.

Whether or not the loss you observe due to integer scaling or due to overlap of the features in the pixel space is significant will depend on the specific application. It's something that needs to be kept in mind, but I don't think it invalidates the methods general usefulness.

**Comment by kaboroevich** [comment]
I added the requested method. It will take an image array or batch of image arrays and return the original feature space. Features that were mapped to the same pixel will receive the same value so it's preferable to have a single feature per pixel. One approach would be to use [UMAP](https://umap-learn.readthedocs.io/en/latest/) as the feature extractor and set `discretization='assignment'` to reduce the amount of overlap. 

Do note that depending on the output of the feature extractor, the [scipy.optimize.linear_sum_assignment](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linear_sum_assignment.html) use by `discretization='assignment'` can take a very long time.
